kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
  name: consumidor-mensagens
  labels:
    app: consumidor-mensagens
    app.kubernetes.io/component: consumidor-mensagens
    app.kubernetes.io/instance: consumidor-mensagens
    app.kubernetes.io/name: consumidor-mensagens
    app.kubernetes.io/part-of: aplicacoes
    app.openshift.io/runtime: camel
    app.openshift.io/runtime-namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumidor-mensagens
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consumidor-mensagens
        deployment: consumidor-mensagens
    spec:
      containers:
        - name: consumidor-mensagens
          image: >-
            quay.io/vflorent/consumidor-mensagens-jvm
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler