kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
  name: consumidor-respostas
  labels:
    app: consumidor-respostas
    app.kubernetes.io/component: consumidor-respostas
    app.kubernetes.io/instance: consumidor-respostas
    app.kubernetes.io/name: consumidor-respostas
    app.kubernetes.io/part-of: aplicacoes
    app.openshift.io/runtime: camel
    app.openshift.io/runtime-namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumidor-respostas
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consumidor-respostas
        deployment: consumidor-respostas
    spec:
      containers:
        - name: consumidor-respostas
          image: >-
            quay.io/vflorent/consumidor-respostas-jvm
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

---
kind: Service
apiVersion: v1
metadata:
  name: consumidor-respostas
  namespace: poc
  labels:
    app: consumidor-respostas
    app.kubernetes.io/component: consumidor-respostas
    app.kubernetes.io/instance: consumidor-respostas
    app.kubernetes.io/name: consumidor-respostas
    app.kubernetes.io/part-of: aplicacoes
    app.openshift.io/runtime: camel
    app.openshift.io/runtime-namespace: poc
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: consumidor-respostas
status:
  loadBalancer: {}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: consumidor-respostas
  namespace: poc
  labels:
    app: consumidor-respostas
    app.kubernetes.io/component: consumidor-respostas
    app.kubernetes.io/instance: consumidor-respostas
    app.kubernetes.io/name: consumidor-respostas
    app.kubernetes.io/part-of: aplicacoes
    app.openshift.io/runtime: camel
    app.openshift.io/runtime-namespace: poc
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: consumidor-respostas
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None

