kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
  name: gerador-mensagens
  labels:
    app: gerador-mensagens
    app.kubernetes.io/component: gerador-mensagens
    app.kubernetes.io/instance: gerador-mensagens
    app.kubernetes.io/name: gerador-mensagens
    app.kubernetes.io/part-of: aplicacoes
    app.openshift.io/runtime: camel
    app.openshift.io/runtime-namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerador-mensagens
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gerador-mensagens
        deployment: gerador-mensagens
    spec:
      containers:
        - name: gerador-mensagens
          image: >-
            quay.io/hodrigohamalho/gerador-mensagens-jvm
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler