apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: oracle-database-sink-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-source
    properties:
      bootstrapServers: "my-source-cluster-kafka-bootstrap.poc.svc:9092"
      topic: mssql-server-linux.dbo.Orders
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: oracle-database-sink
    properties:
      serverName: oracle-19c-orapoc
      serverPort: 1521
      username: ot
      password: Orcl1234
      databaseName: ORAPOCPDB
      query: INSERT INTO ot.orders (order_id,type,flavor,quantity,price,sender_user)      VALUES(:#OrderId,:#OrderType,:#OrderItemName,:#Quantity,:#Price,:#OrderUser)
