- name: Message Generator
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'gerador-mensagens.yml') }}"

- name: Message Consumer
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'consumidor-mensagens.yml') }}"

- name: SOAP Mock
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'soap-mock.yml') }}"

- name: Response Consumer
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'consumidor-respostas.yml') }}"

- name: Create Oracle Sink Connector
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'kafka-connector-camel-sql.yml') }}"