- name: Remove limit range
  shell: oc delete limitranges --all -n {{ namespace }}
  args:
    executable: /bin/bash

- name: Create Oracle Service Account
  shell: oc create sa oracle -n {{ namespace }}
  ignore_errors: yes
  args:
    executable: /bin/bash

- name: Anyuid permission to oracle service account 
  shell: oc adm policy add-scc-to-user anyuid -z oracle -n {{ namespace }}
  args:
    executable: /bin/bash

- name: Evaluate Oracle Password Secret
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'oracle-password-secret.yml') }}"

- name: Evaluate Oracle Persistence Volume
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'oracle-pv.yml') }}"

- name: Evaluate Oracle Instance
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'oracle-deployment.yml') }}"

- name: Evaluate Oracle Service
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('file', 'oracle-service.yml') }}"    

- name: Enable anyuid on Namespace
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('template', 'scc-anyuid.yaml.j2') }}"
  vars:
    scc_namespace: '{{ namespace }}'

- name: Create Data SQL ConfigMap for SQL Server
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('template', 'configmap-data-sql.yaml.j2') }}"

- name: Deploy MS SQL Server Database
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('template', 'mssql-server-linux.yaml.j2') }}"

- name: Wait for Database to Start
  k8s_info:
    kind: Deployment
    name: mssql-server-linux
    namespace: '{{ namespace }}'
    api_version: apps/v1
  register: mssql_resource
  until: >-
    (mssql_resource.resources is defined)
    and (mssql_resource.resources|length>0)
    and (mssql_resource.resources[0].status is defined)
    and (mssql_resource.resources[0].status.readyReplicas is defined)
    and (mssql_resource.resources[0].status.readyReplicas > 0)
  retries: 30
  delay: 10

- name: Configure CDC in Database
  command: >-
    oc -n {{ namespace }} exec deployment/mssql-server-linux --
    /opt/mssql-tools/bin/sqlcmd -S mssql-server-linux -U sa -P 'Password!' -i /opt/workshop/data.sql

- name: Deploy MyPHP Legacy App
  k8s:
    state: present
    namespace: '{{ namespace }}'
    resource_definition: "{{ lookup('template', 'apache-php-app.yaml.j2') }}"