ORACLE_DB_POD=$(oc get pod -lapp=oracle-19c-orapoc -ogo-template="{{(index .items 0).metadata.name}}")
POSTGRES_DB_POD=$(oc get pod -lname=postgresql -ogo-template="{{(index .items 0).metadata.name}}")

# # Create user 'OT' with password 'Orcl1234' on the PDB Oracle container and grant CONNECT and RESOURCE rpivileges
oc exec -i $ORACLE_DB_POD -- bash -c 'sqlplus sys/$ORACLE_PWD@$ORACLE_PDB as SYSDBA' <\
  files/create-ot-user.sql

# # As user 'OT', create a test table on the PDB Oracle container and insert test data on it
oc exec -i $ORACLE_DB_POD -- bash -c 'sqlplus ot/Orcl1234@$ORACLE_PDB' <\
  files/create-ot-tables.sql

oc exec -i $ORACLE_DB_POD -- bash -c 'sqlplus ot/Orcl1234@$ORACLE_PDB' <\
  files/create-pmg-table.sql

# # Set up the archivelog functionality on the CDB Oracle container
# # Create a user for Debezium to observe the archive and supplemental logs
# #Add supplemental log support for all columns in the test table
oc exec -i $ORACLE_DB_POD -- bash -c 'sqlplus sys/$ORACLE_PWD as SYSDBA;' <\
  files/setup-archivelog.sql


oc exec -i $POSTGRES_DB_POD -- bash -c 'psql -U redhat -d sampledb;' <\
  files/postgres-otkeys-table.sql

oc exec -i $POSTGRES_DB_POD -- bash -c 'psql -U redhat -d sampledb;' <\
  files/postgres-pmg-table.sql