CREATE TABLE ot.keys(id NUMBER GENERATED BY DEFAULT AS IDENTITY, key VARCHAR2(50) NOT NULL, value VARCHAR2(50) NOT NULL, PRIMARY KEY(id));

-- CREATE TABLE keys (
-- 	id serial PRIMARY KEY,
-- 	key VARCHAR ( 50 ) NOT NULL,
-- 	value VARCHAR ( 50 ) NOT NULL
-- );

INSERT INTO ot.keys(key,value) VALUES('1234567','hodrigohamalho@gmail.com1');
INSERT INTO ot.keys(key,value) VALUES('1234568','rramalho@redhat.com');
