kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orapoc-oradata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem